// Code generated by mockery v2.0.0. DO NOT EDIT.
//
// This is a lightweight, self-contained mock for the training task.
package wifi

import "github.com/mdlayher/wifi"

// MockWiFiHandle is a mock implementation of the WiFiHandle interface.
type MockWiFiHandle struct {
	InterfacesFunc func() ([]*wifi.Interface, error)
	Calls          int
}

func (m *MockWiFiHandle) Interfaces() ([]*wifi.Interface, error) {
	m.Calls++
	if m.InterfacesFunc != nil {
		return m.InterfacesFunc()
	}
	return nil, nil
}
