// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	wifi "github.com/mdlayher/wifi"
	mock "github.com/stretchr/testify/mock"
)

// WiFiHandle is an autogenerated mock type for the WiFiHandle type
type WiFiHandle struct {
	mock.Mock
}

type WiFiHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *WiFiHandle) EXPECT() *WiFiHandle_Expecter {
	return &WiFiHandle_Expecter{mock: &_m.Mock}
}

// Interfaces provides a mock function with no fields
func (_m *WiFiHandle) Interfaces() ([]*wifi.Interface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interfaces")
	}

	var r0 []*wifi.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*wifi.Interface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*wifi.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*wifi.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WiFiHandle_Interfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Interfaces'
type WiFiHandle_Interfaces_Call struct {
	*mock.Call
}

// Interfaces is a helper method to define mock.On call
func (_e *WiFiHandle_Expecter) Interfaces() *WiFiHandle_Interfaces_Call {
	return &WiFiHandle_Interfaces_Call{Call: _e.mock.On("Interfaces")}
}

func (_c *WiFiHandle_Interfaces_Call) Run(run func()) *WiFiHandle_Interfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WiFiHandle_Interfaces_Call) Return(_a0 []*wifi.Interface, _a1 error) *WiFiHandle_Interfaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WiFiHandle_Interfaces_Call) RunAndReturn(run func() ([]*wifi.Interface, error)) *WiFiHandle_Interfaces_Call {
	_c.Call.Return(run)
	return _c
}

// NewWiFiHandle creates a new instance of WiFiHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWiFiHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WiFiHandle {
	mock := &WiFiHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
